### ISSUE TITLE
Do not see regex line and tab only inserts tab

### ISSUE THREAD

**Issue by SHU-red** [f01c33/rx#3]
Hey there,
im very interested in using your tiny tool which i find is very helpful

As i am using this currently on my windows PC, it seems that
- First line is missing in Windows powershell
- Pressing Tab hides the cursor
- On Pressing tab again the cursor returnes and a tab-character has been inserted

Do you know this problem?
On which OS/shell do you use it?

**Comment by f01c33** [comment]
Hi, thanks for the bug report, I'm currently on Linux. Can you try and use
it on CMD to see if it works there, I'll check it out on my windows box
later to see if I can reproduce the issue.

Em ter., 28 de mai. de 2024 10:39 AM, SHU-red ***@***.***>
escreveu:

**Comment by f01c33** [comment]
I think i fixed the bug @SHU-red , can you try again? sorry for the delay

**Comment by SHU-red** [comment]
using `go: downloading github.com/f01c33/rx v0.0.2-0.20240607203422-b373b381734c`

It looks now very good on my windows machine
Thank you very very much for this handy tool

using it very often
